// src/app/signup/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { EmailSignUpForm } from "@/components/auth/email-sign-up-form";
import { GitHubSignUpButton } from "@/components/auth/github-sign-up-button";
import { GoogleSignUpButton } from "@/components/auth/google-sign-up-button";
import { BackButton } from "@/components/back-button";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
	title: "Sign Up",
	description: "Create your account",
};

export default async function SignUpPage() {
	const session = await getSession();

	// If already logged in, redirect to homepage
	if (session) {
		redirect("/");
	}

	return (
		<div className="flex min-h-screen items-center justify-center p-4">
			<div className="w-full max-w-md space-y-8">
				<BackButton />
				<div className="text-center">
					<h1 className="text-3xl font-bold tracking-tight">Create Account</h1>
					<p className="mt-2 text-sm text-muted-foreground">
						Get started with your free account
					</p>
				</div>

				<div className="mt-8 space-y-6">
					{/* Social Sign-Up */}
					<div className="space-y-3">
						<GoogleSignUpButton />
						<GitHubSignUpButton />
					</div>

					<div className="relative">
						<div className="absolute inset-0 flex items-center">
							<span className="w-full border-t" />
						</div>
						<div className="relative flex justify-center text-xs uppercase">
							<span className="bg-background px-2 text-muted-foreground">
								Or continue with email
							</span>
						</div>
					</div>

					{/* Email/Password Sign-Up */}
					<EmailSignUpForm />

					<p className="text-center text-sm text-muted-foreground">
						By signing up, you agree to our Terms of Service and Privacy Policy
					</p>
				</div>

				<div className="text-center">
					<p className="text-sm text-muted-foreground">
						Already have an account?{" "}
						<Link
							href="/login"
							className="font-medium text-primary hover:underline"
						>
							Sign in
						</Link>
					</p>
				</div>
			</div>
		</div>
	);
}

// src/routes/(public)/signup/+page.svelte
<script lang="ts">
import { enhance } from "$app/forms";
import IconGithub from "$lib/components/IconGithub.svelte";
import IconGoogle from "$lib/components/IconGoogle.svelte";
import type { ActionData, PageData } from "./$types";

let { form, data }: { form: ActionData; data: PageData } = $props();

// bg-surface keeps inputs on-theme; unset background renders white in most browsers.
const inputClass =
	"w-full rounded-sm border border-border bg-surface px-3 py-2 font-[inherit] text-text focus:border-accent focus:ring-1 focus:ring-accent";
</script>

<svelte:head>
	<title>Sign up · Omnilog</title>
</svelte:head>

<div class="mx-auto my-16 max-w-100 px-4">
	<h1>Create your account</h1>

	<div class="mt-6 flex flex-col gap-3">
		<a
			href="/login/github?next={encodeURIComponent(data.next)}"
			class="flex items-center justify-center gap-2 rounded-sm border border-border px-4 py-2.5 text-text no-underline transition-colors hover:border-text-muted hover:bg-surface"
		>
			<IconGithub size={18} />
			Continue with GitHub
		</a>
		<a
			href="/login/google?next={encodeURIComponent(data.next)}"
			class="flex items-center justify-center gap-2 rounded-sm border border-border px-4 py-2.5 text-text no-underline transition-colors hover:border-text-muted hover:bg-surface"
		>
			<IconGoogle size={18} />
			Continue with Google
		</a>
	</div>

	<div class="my-6 flex items-center gap-3 text-sm text-text-muted">
		<div class="h-px flex-1 bg-border"></div>
		or
		<div class="h-px flex-1 bg-border"></div>
	</div>

	<form method="post" use:enhance class="flex flex-col gap-4">
		<input type="hidden" name="next" value={data.next} />

		<label class="flex flex-col gap-1 text-sm text-text-muted">
			Email
			<input
				type="email"
				name="email"
				value={form?.email ?? ""}
				required
				autocomplete="email"
				class={inputClass}
			/>
		</label>

		<label class="flex flex-col gap-1 text-sm text-text-muted">
			Username
			<input
				type="text"
				name="username"
				value={form?.username ?? ""}
				required
				autocomplete="username"
				minlength="3"
				maxlength="31"
				class={inputClass}
			/>
		</label>

		<label class="flex flex-col gap-1 text-sm text-text-muted">
			Password
			<input
				type="password"
				name="password"
				required
				autocomplete="new-password"
				minlength="8"
				class={inputClass}
			/>
		</label>

		{#if form?.message}
			<p class="m-0 text-danger">{form.message}</p>
		{/if}

		<button
			type="submit"
			class="cursor-pointer rounded-sm border-none bg-accent px-6 py-2.5 font-[inherit] text-bg transition-opacity hover:opacity-90"
		>
			Sign up
		</button>
	</form>

	<p class="text-text-muted">
		Already have an account?
		<a href="/login?next={data.next}" class="text-accent no-underline hover:text-text">Log in</a>
	</p>
</div>
