// src/app/login/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { EmailSignInForm } from "@/components/auth/email-sign-in-form";
import { GitHubSignInButton } from "@/components/auth/github-sign-in-button";
import { GoogleSignInButton } from "@/components/auth/google-sign-in-button";
import { BackButton } from "@/components/back-button";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
	title: "Login",
	description: "Sign in to your account",
};

export default async function LoginPage() {
	const session = await getSession();

	// If already logged in, redirect to dashboard
	if (session) {
		redirect("/dashboard");
	}

	return (
		<div className="flex min-h-screen items-center justify-center p-4">
			<div className="w-full max-w-md space-y-8">
				<BackButton />
				<div className="text-center">
					<h1 className="text-3xl font-bold tracking-tight">Welcome Back</h1>
					<p className="mt-2 text-sm text-muted-foreground">
						Sign in to your account to continue
					</p>
				</div>

				<div className="mt-8 space-y-6">
					{/* Social Sign-In */}
					<div className="space-y-3">
						<GoogleSignInButton />
						<GitHubSignInButton />
					</div>

					<div className="relative">
						<div className="absolute inset-0 flex items-center">
							<span className="w-full border-t" />
						</div>
						<div className="relative flex justify-center text-xs uppercase">
							<span className="bg-background px-2 text-muted-foreground">
								Or continue with email
							</span>
						</div>
					</div>

					{/* Email/Password Sign-In */}
					<EmailSignInForm />
				</div>

				<div className="text-center">
					<p className="text-sm text-muted-foreground">
						Don't have an account?{" "}
						<Link
							href="/signup"
							className="font-medium text-primary hover:underline"
						>
							Sign up
						</Link>
					</p>
				</div>
			</div>
		</div>
	);
}

// src/routes/(public)/login/+page.svelte
<script lang="ts">
import { enhance } from "$app/forms";
import IconGithub from "$lib/components/IconGithub.svelte";
import IconGoogle from "$lib/components/IconGoogle.svelte";
import { INPUT_CLASS } from "$lib/form-styles";
import type { ActionData, PageData } from "./$types";

let { form, data }: { form: ActionData; data: PageData } = $props();
</script>

<svelte:head>
	<title>Log in · Omnilog</title>
</svelte:head>

<div class="mx-auto my-16 max-w-100 px-4">
	<h1>Welcome back</h1>

	{#if data.resetSuccess}
		<p class="mt-2 rounded-sm border border-accent px-3 py-2 text-sm text-accent">
			Password reset — log in with your new password.
		</p>
	{/if}

	<div class="mt-6 flex flex-col gap-3">
		<a
			href="/login/github?next={encodeURIComponent(data.next)}"
			class="flex items-center justify-center gap-2 rounded-sm border border-border px-4 py-2.5 text-text no-underline transition-colors hover:border-text-muted hover:bg-surface"
		>
			<IconGithub size={18} />
			Continue with GitHub
		</a>
		<a
			href="/login/google?next={encodeURIComponent(data.next)}"
			class="flex items-center justify-center gap-2 rounded-sm border border-border px-4 py-2.5 text-text no-underline transition-colors hover:border-text-muted hover:bg-surface"
		>
			<IconGoogle size={18} />
			Continue with Google
		</a>
	</div>

	<div class="my-6 flex items-center gap-3 text-sm text-text-muted">
		<div class="h-px flex-1 bg-border"></div>
		or
		<div class="h-px flex-1 bg-border"></div>
	</div>

	<form method="post" use:enhance class="flex flex-col gap-4">
		<input type="hidden" name="next" value={data.next} />

		<label class="flex flex-col gap-1 text-sm text-text-muted">
			Username
			<input
				type="text"
				name="username"
				value={form?.username ?? ""}
				required
				autocomplete="username"
				class={INPUT_CLASS}
			/>
		</label>

		<label class="flex flex-col gap-1 text-sm text-text-muted">
			Password
			<input
				type="password"
				name="password"
				required
				autocomplete="current-password"
				class={INPUT_CLASS}
			/>
		</label>

		<a href="/forgot-password" class="self-end text-sm text-accent no-underline hover:text-text">
			Forgot password?
		</a>

		{#if form?.message}
			<p class="m-0 text-danger">{form.message}</p>
		{/if}

		<button
			type="submit"
			class="cursor-pointer rounded-sm border-none bg-accent px-6 py-2.5 font-[inherit] text-bg transition-opacity hover:opacity-90"
		>
			Log in
		</button>
	</form>

	<p class="text-text-muted">
		Don't have an account?
		<a href="/signup?next={data.next}" class="text-accent no-underline hover:text-text">Sign up</a>
	</p>
</div>
