// src/app/login/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { EmailSignInForm } from "@/components/auth/email-sign-in-form";
import { GitHubSignInButton } from "@/components/auth/github-sign-in-button";
import { GoogleSignInButton } from "@/components/auth/google-sign-in-button";
import { BackButton } from "@/components/back-button";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
	title: "Login",
	description: "Sign in to your account",
};

export default async function LoginPage() {
	const session = await getSession();

	// If already logged in, redirect to dashboard
	if (session) {
		redirect("/dashboard");
	}

	return (
		<div className="flex min-h-screen items-center justify-center p-4">
			<div className="w-full max-w-md space-y-8">
				<BackButton />
				<div className="text-center">
					<h1 className="text-3xl font-bold tracking-tight">Welcome Back</h1>
					<p className="mt-2 text-sm text-muted-foreground">
						Sign in to your account to continue
					</p>
				</div>

				<div className="mt-8 space-y-6">
					{/* Social Sign-In */}
					<div className="space-y-3">
						<GoogleSignInButton />
						<GitHubSignInButton />
					</div>

					<div className="relative">
						<div className="absolute inset-0 flex items-center">
							<span className="w-full border-t" />
						</div>
						<div className="relative flex justify-center text-xs uppercase">
							<span className="bg-background px-2 text-muted-foreground">
								Or continue with email
							</span>
						</div>
					</div>

					{/* Email/Password Sign-In */}
					<EmailSignInForm />
				</div>

				<div className="text-center">
					<p className="text-sm text-muted-foreground">
						Don't have an account?{" "}
						<Link
							href="/signup"
							className="font-medium text-primary hover:underline"
						>
							Sign up
						</Link>
					</p>
				</div>
			</div>
		</div>
	);
}

// src/routes/auth/login/+page.svelte
<script lang="ts">
	import { Button } from "$lib/components/ui/button";
	import * as Card from "$lib/components/ui/card";
	import { Input } from "$lib/components/ui/input";
	import { Label } from "$lib/components/ui/label";
	import { Icons } from "$lib/components/icons";
</script>

<div class="flex h-[calc(100vh-72px)] w-full items-center justify-center">
	<Card.Root class="w-full max-w-sm rounded-lg border bg-card text-card-foreground shadow-sm">
		<Card.Header>
			<Card.Title class="text-2xl">Login</Card.Title>
		</Card.Header>
		<Card.Content class="flex w-full flex-col justify-between gap-2">
			<div class="grid gap-2">
				<Label for="email">Email</Label>
				<Input id="email" type="email" placeholder="example@example.com" />
			</div>
			<div class="grid gap-2">
				<Label for="password">Password</Label>
				<Input id="password" type="password" />
			</div>
			<Button disabled class="w-full">Sign In</Button>

			<div class="relative">
				<div class="absolute inset-0 flex items-center">
					<span class="w-full border-t" />
				</div>
				<div class="relative flex justify-center text-xs uppercase">
					<span class="bg-card px-2 text-muted-foreground"> Or continue with </span>
				</div>
			</div>

			<Button href="/auth/login/github">
				<Icons.github class="mr-2 h-4 w-4" />
				Github
			</Button>
			<Button disabled class="hover:cursor-not-allowed">
				<Icons.google class="mr-2 h-4 w-4" />
				Google
			</Button>
			<!-- <div class="relative">
				<div class="absolute inset-0 flex items-center">
					<span class="w-full border-t" />
				</div>
				<div class="relative flex justify-center text-xs uppercase">
					<span class="px-2 bg-card text-muted-foreground"> Or continue with </span>
				</div>
			</div> -->
		</Card.Content>
	</Card.Root>
</div>
